### ISSUE TITLE
RLS fails to start because of the nightly toolchain specified with date

### ISSUE THREAD

**Issue by SebastianElvis** [rust-lang/rls-vscode#503]
## VSCode

Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-45-generic

## Rust Toolchains installed (by rustup)

stable-x86_64-unknown-linux-gnu
nightly-2019-01-15-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

## Description

The newest Rust nightly build is 1.34. However, this version seems to have no RLS server at present. 
Therefore, I used 1.33 by specifying the date when doing `rustup toolchain install`.
However, if keeping the `"rust-client.channel"` setting in VSCode as `"nightly"`, the RLS cannot start as normal.
I successfully started RLS by setting `"rust-client.channel": "nightly-2019-01-15"`. This setting was not prompted and treated as an unrecognized value.
I guess the current rls-vscode implementation concats the "rust-client.channel" setting with other stuff like OS and architecture to produce the correct toolchain name, then finds the toolchain, and finally launches the RLS. However, some details like prompts and config validations are ignored.

**Comment by JoshLambda** [comment]
As a workaround one can add `"rust-client.disableRustup": true` in settings. I didn't notice any loss of functionality doing so. And this way one can work with any toolchain date without having to change settings.

By the way, this bug also appears when `rust-client.channel` isn't set at all, whatever the toolchain may be (with or without date).

**Comment by angusgraham** [comment]
@JoshLambda  The issue where it doesn't work if rust-client.channel is not set is fixed in 0.5.4

**Comment by JoshLambda** [comment]
@angusgraham Thanks for the info, that's good to know.

**Comment by Xanewok** [comment]
This should be fixed now, so closing.

**Comment by LifeIsStrange** [comment]
This is not fixed, I am currenlty having the issue on nightly 1.36.
Even when setting rust-client.disableRustup to true. (switching from stable to nightly work while vscode is running, but when I relaunch RLS crash 5 time and stop working.)
RLS works fine on stable.

**Comment by GuilhermeWerner** [comment]
I'm having the same problem here

**VSCode** 1.52.1 x64 ea3859d4ba2f3e577a159bc91e3074c5d85c0523
**Windows** 10 Pro x64 20H2 19042.746

**Rust Toolchains:**
stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc
