### ISSUE TITLE
Error installing RLS on MacOS Sierra

### ISSUE THREAD

**Issue by greg5678** [rust-lang/rls-vscode#521]
I've edited the `settings.json` file and fixed the previous issue [here](https://github.com/rust-lang/rls-vscode/issues/517). Now when I try to run Rust code in VSCode I get `RLS not installed. Install?`, but it is already installed.

**Comment by Xanewok** [comment]
I believe this can be related to #522? What's your `rustup` version?

**Comment by greg5678** [comment]
`rustup 1.17.0 (069c88ed6 2019-03-05)`

**Comment by greg5678** [comment]
Any idea what the issue is?

**Comment by angusgraham** [comment]
@greg5678 An explanation of the issue and a workaround is in https://github.com/rust-lang/rls-vscode/issues/517

**Comment by mati865** [comment]
It's fixed in latest version, update your extension.

**Comment by angusgraham** [comment]
@mati865 I'm on v0.5.4 and I still get "RLS could not be started" if I remove "rust-client.channel":"stable" from my settings.json

**Comment by mati865** [comment]
@angusgraham have you restarted VS Code after the update?
Check console from Developer Tools, maybe there is another bug.

**Comment by angusgraham** [comment]
Oh weird it's working now. I thought I had restarted after the update but maybe not. Cheers @mati865

**Comment by greg5678** [comment]
I still keep getting the same error as before after updating rls-vscode to 0.5.4.

**Comment by mati865** [comment]
Did you restart VS Code?

**Comment by greg5678** [comment]
Yes, more than once.

**Comment by Xanewok** [comment]
@greg5678 what is your `rustc --version`? Could you post the output of `$ rustup component list`?
