### ISSUE TITLE
why unkonwn rls configuration use_crate_blacklist 

### ISSUE THREAD

**Issue by theone-pang** [rust-lang/rls-vscode#639]
open project show "unkonwn rls configuration use_crate_blacklist " tip evry time,why?

**Comment by greensirius** [comment]
I have the same issues here on my vscode, my current rls is 1.38.0

**Comment by mati865** [comment]
It's because of https://github.com/rust-lang/rls/pull/1509
cc @Xanewok

**Comment by Xanewok** [comment]
Yup, will push a new extension version today.

Sorry for the inconvenience.

**Comment by arlyon** [comment]
Any update on this? Still getting this issue

**Comment by Xanewok** [comment]
Sorry for the delay! I'll publish a version when https://github.com/rust-lang/rust/pull/63472 is merged upstream (it looks like it's going to be tomorrow) - with this, the RLS will be able to emit a user friendly error whenever `use_crate_backlist` is still specified.

**Comment by zuobaoquan** [comment]
Workaround for VSCode:   add `"rust.use_crate_blacklist": false` to settings.json and restart the editor.

**Comment by mati865** [comment]
It's fixed in up upcoming nightly release.

**Comment by Xanewok** [comment]
This was fixed in the newest RLS edition and a new version of the extension was published, so this shouldn't pop up anymore.

**Comment by stefanos82** [comment]
Nope, still the same issue, even with 0.6.3

![image](https://user-images.githubusercontent.com/1777466/64479822-2ae62880-d1c5-11e9-832a-f9c712d9439d.png)
P.S.: I've just started learning Rust and installed this extension; it's the very first message I got...nice welcoming :rofl:

**Comment by mati865** [comment]
New RLS wasn't yet merged into rust.

**Comment by stefanos82** [comment]
> This was fixed in the newest RLS edition and a new version of the extension was published, so this shouldn't pop up anymore.

I based my reply on this quote.

**Comment by AkariAkaori** [comment]
Still getting it with `rls 1.39.0 (80a1d34 2019-09-20)` and extension 0.6.3, don't have `use_crate_blacklist` anywhere in my project directory or user settings.json

**Comment by dashed** [comment]
@Xanewok For some reason, I'm receiving this warning for rust projects. I'm using v0.6.3 of rls-vscode 😕

**Comment by Xanewok** [comment]
Please update the extension to the 0.7 version, the Rust toolchain to 1.38 and let me know if the problem still persists, thanks!

**Comment by stefanos82** [comment]
The issue remains the same with a slightly different message this time: 
![image](https://user-images.githubusercontent.com/1777466/66960789-f5f7ac00-f075-11e9-93e3-cdd9c34df895.png)
